image: "ubuntu:20.04"
# TODO: move to macaronios/funtoo-minimal soon.
env:
- GCC_VERSION=10
- ARCH={{.Values.arch}}
- KERNEL_PREFIX=vanilla
- SUFFIX={{ .Values.suffix }}
- KERNEL_TYPE={{ .Values.prefix }}
prelude:
- |
  export DEBIAN_FRONTEND=noninteractive && \
  apt-get update               && \
  apt-get -y -q upgrade        && \
  apt-get install -y -q apt-utils dialog zstd \
      xz-utils wget sudo aptitude flex bison libncurses5-dev make git exuberant-ctags bc libssl-dev libelf-dev \
      gcc-${GCC_VERSION} g++-${GCC_VERSION} gcc-${GCC_VERSION}-plugin-dev gcc g++ \
      gcc-${GCC_VERSION}-aarch64-linux-gnu g++-${GCC_VERSION}-aarch64-linux-gnu \
      gcc-aarch64-linux-gnu g++-aarch64-linux-gnu && \
      apt-get install -y -q gcc-${GCC_VERSION}-plugin-dev-aarch64-linux-gnu
- bash prepare.sh
steps:
- bash build.sh
package_dir: /luetbuild/output
