image: "macaronios/funtoo-minimal:latest-amd64"
steps:
- >-
  luet repo update &&
  luet upgrade -y &&
  luet i --sync-repos utils/jq utils/yq -y &&
  luet cleanup &&
  mkdir /{{ .Values.name }}/usr/share/macaroni/entities -p &&
  TARGET_DIR=/{{ .Values.name }}/usr/share/macaroni/entities/
  bash scripts/generator.sh
package_dir: /{{ .Values.name }}
