steps:
- bash build.sh
package_dir: /luetbuild/modules
requires:
- name: "macaroni-zen-full"
  category: "kernel-6.7"
  version: ">=0"
env:
- KERNEL_PREFIX=zen
- SUFFIX={{ .Values.suffix }}
excludes:
- /boot/vmlinuz-.*
- /build.sh$
- /build.yaml$
- /definition.yaml$
