image: "macaronios/terragon-minimal:latest-amd64"
prelude:
- >-
  luet repo update &&
  luet i dev-vcs/git sys-apps/portage -y &&
  luet cleanup &&
  git clone https://github.com/{{ ( index .Values.labels "github.owner" ) }}/{{ .Values.name }}.git &&
  cd {{ .Values.name }} && ls -l &&
  git checkout {{ ( index .Values.labels "git.sha" ) }} &&
  mkdir -p /{{ .Values.name }}/usr/share/macaroni/{{ .Values.name }} &&
  cd catalog &&
  cp -rvf eclass /{{ .Values.name }}/usr/share/macaroni/{{ .Values.name }}/ &&
  cp -rvf commons /{{ .Values.name }}/usr/share/macaroni/{{ .Values.name }}/
package_dir: /{{ .Values.name }}
