image: macaronios/terragon-minimal:latest-amd64
prelude:
- >-
  luet repo update &&
  luet i -y upx-bin git make go virtual/base &&
  mkdir /tmp &&
  git clone https://github.com/${GITHUB_ORG}/${PACKAGE_NAME}.git
env:
- GITHUB_ORG={{ ( index .Values.labels "github.owner" ) }}
- GIT_HASH=v{{ .Values.version }}
package_dir: /{{ .Values.name }}
steps:
- >-
  cd ${PACKAGE_NAME} &&
  git checkout "${GIT_HASH%\+*}" &&
  make build &&
  mkdir -p /{{ .Values.name }}/usr/bin/ &&
  mv ${PACKAGE_NAME} /{{ .Values.name }}/usr/bin/${PACKAGE_NAME} &&
  cd /{{ .Values.name }}/usr/bin &&
  ln -s ${PACKAGE_NAME} luet-portage-converter
