image: macaronios/terragon-testing-minimal:latest-amd64
prelude:
- >-
  luet i -y --sync-repos --purge-repos make upx-bin go ca-certificates git &&
  mkdir /tmp/ &&
- git clone https://github.com/${GITHUB_ORG}/${GITHUB_NAME}.git
env:
- GITHUB_ORG=macaroni-os
- GITHUB_NAME={{ ( index .Values.labels "github.owner" ) }}
- GIT_HASH=v{{ .Values.version }}
package_dir: /{{ .Values.name }}
steps:
- >-
  cd ${GITHUB_NAME} &&
  git checkout "${GIT_HASH%\+*}" &&
  make build-small &&
  mkdir -p /{{ .Values.name }}/usr/bin &&
  mkdir -p /{{ .Values.name }}/usr/share/macaroni/browsers/ &&
  mv ${GITHUB_NAME} /{{ .Values.name }}/usr/bin/${GITHUB_NAME} &&
  cp contrib/browsers-catalog/macaroni.yml /{{ .Values.name }}/usr/share/macaroni/browsers/catalog
