image: macaronios/terragon-testing-minimal:latest-amd64
prelude:
- >-
  luet i -y --sync-repos --purge-repos --cleanup make upx-bin go ca-certificates git &&
  mkdir /tmp/ &&
  git clone https://github.com/${GITHUB_ORG}/${GITHUB_NAME}.git
env:
- GITHUB_ORG=geaaru
- GIT_HASH=v{{ .Values.version }}
package_dir: /{{ .Values.name }}
steps:
- >-
  cd ${PACKAGE_NAME} &&
  git checkout "${GIT_HASH%\+*}" &&
  make build &&
  mkdir -p /{{ .Values.name }}/usr/bin &&
  mv ${PACKAGE_NAME} /{{ .Values.name }}/usr/bin/${PACKAGE_NAME}
